use crate::app::{Message, Overlay};
use crate::ui::components::chrome_button::{self, ButtonEmphasis};
use iced::widget::{Space, button, column, container, row, text, text_input};
use iced::{Alignment, Background, Border, Color, Element, Length, Shadow};

pub fn view(state: &Overlay) -> Element<'_, Message> {
    let save_settings = button(if state.is_saving_settings {
        "Saving..."
    } else {
        "Save Settings"
    })
    .padding([12, 16])
    .on_press_maybe((!state.is_saving_settings).then_some(Message::SaveSettings));

    let shell = container(
        column![
            row![
                column![
                    text("Settings").size(30),
                    text("Configure OpenRouter once and keep the HUD focused on dictation.")
                        .size(14)
                        .color(Color::from_rgba8(226, 232, 240, 0.72)),
                ]
                .spacing(4),
                Space::new().width(Length::Fill),
                chrome_button::view("✕", Some(Message::CloseSettingsView), ButtonEmphasis::Neutral),
            ]
            .width(Length::Fill)
            .align_y(Alignment::Center),
            container(
                column![
                    section_title("OpenRouter"),
                    text_input(
                        "OpenRouter API key",
                        &state.settings_form.openrouter_api_key
                    )
                    .on_input(Message::SettingsApiKeyChanged)
                    .padding([12, 14]),
                    text_input("Model", &state.settings_form.openrouter_model)
                        .on_input(Message::SettingsModelChanged)
                        .padding([12, 14]),
                    row![
                        save_settings,
                        state
                            .settings_note
                            .as_ref()
                            .map(|note| {
                                text(note)
                                    .size(12)
                                    .color(Color::from_rgba8(148, 163, 184, 0.88))
                            })
                            .unwrap_or_else(|| text("")),
                    ]
                    .spacing(12)
                    .align_y(Alignment::Center),
                ]
                .spacing(14),
            )
            .padding(18)
            .style(|_| card_style()),
            container(
                column![
                    section_title("Runtime"),
                    status_row("Clipboard", "automatic copy after transcription"),
                    status_row("Storage", "~/.config/openvoice/settings.json"),
                    status_row("Audio", "WAV mono 16kHz sent to OpenRouter"),
                ]
                .spacing(12),
            )
            .padding(18)
            .style(|_| card_style()),
            state
                .error
                .as_ref()
                .map(|error| {
                    container(
                        column![
                            text("Issue")
                                .size(13)
                                .color(Color::from_rgb8(251, 146, 60)),
                            text(error)
                                .size(16)
                                .color(Color::from_rgb8(255, 207, 164)),
                        ]
                        .spacing(8),
                    )
                    .padding(18)
                    .style(|_| error_style())
                })
                .unwrap_or_else(|| {
                    container(
                        text("This panel is generated by OpenVoice. Validate your OpenRouter setup before relying on it in production.")
                            .size(12)
                            .color(Color::from_rgba8(226, 232, 240, 0.66)),
                    )
                    .padding([0, 4])
                }),
        ]
        .spacing(18),
    )
    .width(Length::Fill)
    .height(Length::Fill)
    .padding(20)
    .style(|_| {
        container::Style::default()
            .background(Background::Color(Color::from_rgba8(4, 8, 14, 0.96)))
            .border(Border {
                color: Color::from_rgba8(94, 234, 212, 0.16),
                width: 1.0,
                radius: 24.0.into(),
            })
            .shadow(Shadow {
                color: Color::from_rgba8(0, 0, 0, 0.34),
                offset: iced::Vector::new(0.0, 24.0),
                blur_radius: 42.0,
            })
            .color(Color::from_rgb8(248, 250, 252))
    });

    container(shell)
        .width(Length::Fill)
        .height(Length::Fill)
        .padding(12)
        .into()
}

fn section_title(label: &'static str) -> Element<'static, Message> {
    text(label)
        .size(13)
        .color(Color::from_rgba8(148, 163, 184, 0.9))
        .into()
}

fn status_row(label: &'static str, value: &'static str) -> Element<'static, Message> {
    row![
        text(label)
            .size(13)
            .color(Color::from_rgba8(148, 163, 184, 0.82)),
        Space::new().width(Length::Fill),
        text(value).size(13),
    ]
    .into()
}

fn card_style() -> container::Style {
    container::Style::default()
        .background(Background::Color(Color::from_rgba8(8, 14, 20, 0.74)))
        .border(Border {
            color: Color::from_rgba8(94, 234, 212, 0.12),
            width: 1.0,
            radius: 18.0.into(),
        })
        .color(Color::from_rgb8(248, 250, 252))
}

fn error_style() -> container::Style {
    container::Style::default()
        .background(Background::Color(Color::from_rgba8(120, 18, 24, 0.28)))
        .border(Border {
            color: Color::from_rgba8(248, 113, 113, 0.24),
            width: 1.0,
            radius: 18.0.into(),
        })
        .color(Color::from_rgb8(255, 207, 164))
}
